language: python
env:
    - TOXENV=cover
    - TOXENV=py26
    - TOXENV=py27
    # - TOXENV=pypy
    - TOXENV=py32 # no u"" support
    - TOXENV=py33
    # - TOXENV=py34 # No support on Travis-Ci at this time
install:
    - travis_retry pip install tox==1.6.1
script:
    - travis_retry tox